spring:
  application:
    name: Tlias-Web-management
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "050616"

    #Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名配置开关，为true即开启，数据库可将下划线字段数据映射到对象对应驼峰的属性名中
    map-underscore-to-camel-case: true